---
- !ruby/struct:Page
  category: ansible
  date: '2016-03-10'
  title: Reboot on system upgrade
  path: tils/ansible/2016-03-10-reboot_on_system_upgrade.md
- !ruby/struct:Page
  category: anyenv
  date: '2016-02-26'
  title: Change language version
  path: tils/anyenv/2016-02-26-change_language_version.md
- !ruby/struct:Page
  category: crystal
  date: '2016-02-23'
  title: Discovery
  path: tils/crystal/2016-02-23-discovery.md
- !ruby/struct:Page
  category: devops
  date: '2016-02-23'
  title: Anyenv
  path: tils/devops/2016-02-23-anyenv.md
- !ruby/struct:Page
  category: rails
  date: '2016-02-26'
  title: Vulnerability scanner
  path: tils/rails/2016-02-26-vulnerability_scanner.md
- !ruby/struct:Page
  category: rails
  date: '2016-02-26'
  title: Security
  path: tils/rails/2016-02-26-security.md
- !ruby/struct:Page
  category: shell
  date: '2016-02-25'
  title: Check website response time
  path: tils/shell/2016-02-25-check_website_response_time.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-03-08'
  title: All mac addresses in LAN
  path: tils/sysadmin/2016-03-08-all_mac_addresses_in_lan.md
