---
- !ruby/struct:Page
  category: android
  date: '2016-04-30'
  title: Opo factory restore
  path: tils/android/2016-04-30-opo_factory_restore.md
- !ruby/struct:Page
  category: ansible
  date: '2016-03-10'
  title: Reboot on system upgrade
  path: tils/ansible/2016-03-10-reboot_on_system_upgrade.md
- !ruby/struct:Page
  category: anyenv
  date: '2016-02-26'
  title: Change language version
  path: tils/anyenv/2016-02-26-change_language_version.md
- !ruby/struct:Page
  category: crystal
  date: '2016-02-23'
  title: Discovery
  path: tils/crystal/2016-02-23-discovery.md
- !ruby/struct:Page
  category: devops
  date: '2016-02-23'
  title: Anyenv
  path: tils/devops/2016-02-23-anyenv.md
- !ruby/struct:Page
  category: inkscape
  date: '2016-12-06'
  title: Resize svg drawing to canvas
  path: tils/inkscape/2016-12-06-resize_svg_drawing_to_canvas.md
- !ruby/struct:Page
  category: mysql
  date: '2016-03-15'
  title: Mysqldump permissions
  path: tils/mysql/2016-03-15-mysqldump_permissions.md
- !ruby/struct:Page
  category: rails
  date: '2016-02-26'
  title: Vulnerability scanner
  path: tils/rails/2016-02-26-vulnerability_scanner.md
- !ruby/struct:Page
  category: rails
  date: '2016-02-26'
  title: Security
  path: tils/rails/2016-02-26-security.md
- !ruby/struct:Page
  category: rails
  date: '2016-03-17'
  title: Rake tasks specs
  path: tils/rails/2016-03-17-rake_tasks_specs.md
- !ruby/struct:Page
  category: shell
  date: '2016-02-25'
  title: Check website response time
  path: tils/shell/2016-02-25-check_website_response_time.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-03-08'
  title: All mac addresses in LAN
  path: tils/sysadmin/2016-03-08-all_mac_addresses_in_lan.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-04-20'
  title: Uefi external hd boot
  path: tils/sysadmin/2016-04-20-uefi_external_hd_boot.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-04-20'
  title: Change file timestamps
  path: tils/sysadmin/2016-04-20-change_file_timestamps.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-07-12'
  title: Get debconf available selections
  path: tils/sysadmin/2016-07-12-get_debconf_available_selections.md
- !ruby/struct:Page
  category: tils/sysadmin
  date: '2016-09-29'
  title: View last successfull and failed login attempts
  path: tils/tils/sysadmin/2016-09-29-view_last_successfull_and_failed_login_attempts.md
- !ruby/struct:Page
  category: video
  date: '2016-04-20'
  title: Concatenating video files
  path: tils/video/2016-04-20-concatenating_video_files.md
