---
- !ruby/struct:Page
  category: android
  date: '2016-04-30'
  title: Opo factory restore
  path: tils/android/2016-04-30-opo_factory_restore.md
- !ruby/struct:Page
  category: ansible
  date: '2016-03-10'
  title: Reboot on system upgrade
  path: tils/ansible/2016-03-10-reboot_on_system_upgrade.md
- !ruby/struct:Page
  category: anyenv
  date: '2016-02-26'
  title: Change language version
  path: tils/anyenv/2016-02-26-change_language_version.md
- !ruby/struct:Page
  category: crystal
  date: '2016-02-23'
  title: Discovery
  path: tils/crystal/2016-02-23-discovery.md
- !ruby/struct:Page
  category: devops
  date: '2016-02-23'
  title: Anyenv
  path: tils/devops/2016-02-23-anyenv.md
- !ruby/struct:Page
  category: git
  date: '2016-12-23'
  title: Export patch from stash
  path: tils/git/2016-12-23-export_patch_from_stash.md
- !ruby/struct:Page
  category: git
  date: '2020-02-04'
  title: Export subtree with history
  path: tils/git/2020-02-04-export_subtree_with_history.md
- !ruby/struct:Page
  category: git
  date: '2020-02-04'
  title: Import history in another repo
  path: tils/git/2020-02-04-import_history_in_another_repo.md
- !ruby/struct:Page
  category: golang
  date: '2019-12-13'
  title: Use module fork
  path: tils/golang/2019-12-13-use_module_fork.md
- !ruby/struct:Page
  category: golang
  date: '2020-07-30'
  title: Template output as string
  path: tils/golang/2020-07-30-template_output_as_string.md
- !ruby/struct:Page
  category: inkscape
  date: '2016-12-06'
  title: Resize svg drawing to canvas
  path: tils/inkscape/2016-12-06-resize_svg_drawing_to_canvas.md
- !ruby/struct:Page
  category: kubernetes
  date: '2020-04-23'
  title: Recover a crashed node
  path: tils/kubernetes/2020-04-23-recover_a_crashed_node.md
- !ruby/struct:Page
  category: kubernetes
  date: '2020-04-23'
  title: Delete all pods by search
  path: tils/kubernetes/2020-04-23-delete_all_pods_by_search.md
- !ruby/struct:Page
  category: lightdm
  date: '2018-04-06'
  title: Hide user from login screen
  path: tils/lightdm/2018-04-06-hide_user_from_login_screen.md
- !ruby/struct:Page
  category: mysql
  date: '2016-03-15'
  title: Mysqldump permissions
  path: tils/mysql/2016-03-15-mysqldump_permissions.md
- !ruby/struct:Page
  category: postgresql
  date: '2019-10-10'
  title: Specify connection application name
  path: tils/postgresql/2019-10-10-specify_connection_application_name.md
- !ruby/struct:Page
  category: rails
  date: '2016-02-26'
  title: Vulnerability scanner
  path: tils/rails/2016-02-26-vulnerability_scanner.md
- !ruby/struct:Page
  category: rails
  date: '2016-02-26'
  title: Security
  path: tils/rails/2016-02-26-security.md
- !ruby/struct:Page
  category: rails
  date: '2016-03-17'
  title: Rake tasks specs
  path: tils/rails/2016-03-17-rake_tasks_specs.md
- !ruby/struct:Page
  category: ruby
  date: '2020-08-29'
  title: Hide ruby deprecation warnings
  path: tils/ruby/2020-08-29-hide_ruby_deprecation_warnings.md
- !ruby/struct:Page
  category: shell
  date: '2016-02-25'
  title: Check website response time
  path: tils/shell/2016-02-25-check_website_response_time.md
- !ruby/struct:Page
  category: shell
  date: '2020-08-11'
  title: Create huge file
  path: tils/shell/2020-08-11-create_huge_file.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-03-08'
  title: All mac addresses in LAN
  path: tils/sysadmin/2016-03-08-all_mac_addresses_in_lan.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-04-20'
  title: Uefi external hd boot
  path: tils/sysadmin/2016-04-20-uefi_external_hd_boot.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-04-20'
  title: Change file timestamps
  path: tils/sysadmin/2016-04-20-change_file_timestamps.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-07-12'
  title: Get debconf available selections
  path: tils/sysadmin/2016-07-12-get_debconf_available_selections.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-12-06'
  title: See bandwith usage per process
  path: tils/sysadmin/2016-12-06-see_bandwith_usage_per_process.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-12-07'
  title: Show processes using files
  path: tils/sysadmin/2016-12-07-show_processes_using_files.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-12-23'
  title: How to download certificate from server
  path: tils/sysadmin/2016-12-23-how_to_download_certificate_from_server.md
- !ruby/struct:Page
  category: sysadmin
  date: '2017-05-18'
  title: Create encrypted partition
  path: tils/sysadmin/2017-05-18-create_encrypted_partition.md
- !ruby/struct:Page
  category: sysadmin
  date: '2016-09-29'
  title: View last successfull and failed login attempts
  path: tils/sysadmin/2016-09-29-view_last_successfull_and_failed_login_attempts.md
- !ruby/struct:Page
  category: sysadmin
  date: '2017-06-23'
  title: Disable systemd service manually
  path: tils/sysadmin/2017-06-23-disable_systemd_service_manually.md
- !ruby/struct:Page
  category: sysadmin
  date: '2017-11-07'
  title: Show ssh key fingerprint
  path: tils/sysadmin/2017-11-07-show_ssh_key_fingerprint.md
- !ruby/struct:Page
  category: sysadmin
  date: '2017-12-12'
  title: Test starttls smtp auth
  path: tils/sysadmin/2017-12-12-test_starttls_smtp_auth.md
- !ruby/struct:Page
  category: sysadmin
  date: '2018-02-15'
  title: Change ssh key passphrase
  path: tils/sysadmin/2018-02-15-change_ssh_key_passphrase.md
- !ruby/struct:Page
  category: sysadmin
  date: '2018-03-10'
  title: Change gpg expire date
  path: tils/sysadmin/2018-03-10-change_gpg_expire_date.md
- !ruby/struct:Page
  category: sysadmin
  date: '2018-03-10'
  title: Search gpg in keyserver
  path: tils/sysadmin/2018-03-10-search_gpg_in_keyserver.md
- !ruby/struct:Page
  category: sysadmin
  date: '2018-03-10'
  title: Send gpg key to keyserver
  path: tils/sysadmin/2018-03-10-send_gpg_key_to_keyserver.md
- !ruby/struct:Page
  category: sysadmin
  date: '2019-10-11'
  title: List files in deb package
  path: tils/sysadmin/2019-10-11-list_files_in_deb_package.md
- !ruby/struct:Page
  category: terraform
  date: '2020-05-20'
  title: Modules depends on
  path: tils/terraform/2020-05-20-modules_depends_on.md
- !ruby/struct:Page
  category: video
  date: '2016-04-20'
  title: Concatenating video files
  path: tils/video/2016-04-20-concatenating_video_files.md
- !ruby/struct:Page
  category: video
  date: '2017-03-21'
  title: Converting video files
  path: tils/video/2017-03-21-converting_video_files.md
- !ruby/struct:Page
  category: video
  date: '2017-11-07'
  title: Cut video with ffmpeg
  path: tils/video/2017-11-07-cut_video_with_ffmpeg.md
- !ruby/struct:Page
  category: video
  date: '2017-11-07'
  title: Rotate video
  path: tils/video/2017-11-07-rotate_video.md
- !ruby/struct:Page
  category: vim
  date: '2020-09-25'
  title: Read from stdin
  path: tils/vim/2020-09-25-read_from_stdin.md
- !ruby/struct:Page
  category: vim
  date: '2020-09-25'
  title: Send vim buffer to command
  path: tils/vim/2020-09-25-send_vim_buffer_to_command.md
